# Generated by Django 2.2.1 on 2020-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_body',
            name='value',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_host',
            name='response_body',
            field=models.TextField(default='ZZZ', max_length=2000),
        ),
    ]
