# Generated by Django 2.2.1 on 2020-02-26 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xcx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comcp_mk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default=1, max_length=20)),
                ('type', models.CharField(default=1, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('subjection', models.CharField(default='', max_length=20)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录id')),
                ('status', models.CharField(default=1, max_length=20, verbose_name='是否禁用 1用 0禁')),
                ('banner_path', models.CharField(default=1, max_length=20)),
                ('banner_pic_path', models.CharField(max_length=200, verbose_name='banner图片路径')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commodity',
            name='old_login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commodity',
            name='status',
            field=models.CharField(default=1, max_length=20, verbose_name='是否禁用 1用 0禁'),
        ),
        migrations.CreateModel(
            name='Commodity_pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片id')),
                ('status', models.CharField(default=1, max_length=20, verbose_name='是否禁用 1用 0禁')),
                ('pic_path', models.CharField(max_length=200, verbose_name='商品图片路径')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcx.Commodity', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '商品图片表',
            },
        ),
    ]
